services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - django-redis
  
  backend:
    restart: always
    build:
      context: backend
    ports:
      - '8000:8000'
    links:
      - redis
    depends_on:
      - redis
    networks:
      - django-redis
      - react-django

  frontend:
    restart: always
    build:
      context: frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    networks:
      - react-django

networks:
  react-django:
  django-redis: