# Generated by Django 5.2.1 on 2025-05-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('date_added', models.DateField(verbose_name='date added')),
                ('video_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
